### PR TITLE
Add .html to archive file names without extension

### LINKED ISSUE #102: Automatically add .html to generated archives names without extension
Hi,

If you use an archive permalink that is not a directory and not ending by `.html`, such as `/:year`, it generates a file without extension, instead of adding `.html` (unlike with Jekyll's post permalink).

I'd like to add the html extension without having `page.url` containing it (would be the case if you use `/:year.html`).

Note that I actually use the v2.1.1 tagged version.

### PR DESCRIPTION
**Pull request by Exagone313**
Fixes #102.

Read carefully before merging, this may break some configurations, I need your feedback.
Also this is the first time I'm writing Ruby.

### CODE REVIEW

**Comment by Exagone313** [comment]
Hmm, the commit message may not be good as I'm checking for .html$ and not if there isn't an extension.

**Comment by ashmaroli** [comment]
@Exagone313 Are you still interested in getting this merged..?

**Comment by Exagone313** [comment]
It requires some changes but I still want to fix the underlying issue I created.

**Comment by ashmaroli** [comment]
Okay. Apart from amending the original commit message (`git commit --amend`), you may want to check the source code for `Jekyll::Page#destination` and `Jekyll::Document#destination` for logic reference.

**Comment by Exagone313** [comment]
I don't have time to work on this PR, I'm closing it.

**Pull request closed without merging**
