### PR TITLE
Enable incremental operation

### PR DESCRIPTION
**Pull request by mnot**
I put this together quickly, seems to work for me. May need to track other dependencies.

### CODE REVIEW

**Comment by alfredxing** [comment]
Thanks for the pull request! If I remember correctly, the reason I disabled incremental regen completely was because it still doesn't handle the case where posts are added&mdash;that is, while the archives page will be updated with your code, it will not be updated when a new post is created.

**Comment by mnot** [comment]
I tested that case with this patch, works for me.

**Comment by mnot** [comment]
Updated to only write the archives when they change. 

Bit of a messy commit history, sorry.

**Comment by parkr** [comment]
@mnot Would you mind looking into the failures?

**Comment by toolness** [comment]
Hey @parkr, not sure if github notified you of the new commits that @mnot just added, but I figured I'd ping you here just in case it didn't--looks like this PR is passing all travis checks!

**Comment by parkr** [comment]
@toolness this is really @alfredxing's domain 😄

**Comment by parkr** [comment]
@alfredxing I added the @jekyll/archives team which grants members write access to this repo. Feel free to invite anyone you wish!

**Comment by toolness** [comment]
Oh lol, sorry, that was a brain fart on my part :)

Thanks for working on this btw @parkr!  Really really helpful PR. 😁

**Comment by mnot** [comment]
Please do have a good look through before you merge; while it works for me, I've also never really touched Ruby before, so I'm unfamiliar with the idioms, etc.

**Comment by gboone** [comment]
We'd really love to implement this change in our project at 18F/beta.18f.gov. What's the status on this request?

**Comment by parkr** [comment]
On the surface, this LGTM.

**Comment by alfredxing** [comment]
Looks mostly good! Just one question: why keep track of dependencies for archive pages? Most likely we'll need `regenerate: true` on them in case posts are added?

**Comment by mnot** [comment]
That avoids regenerating all of your archives (e.g., all categories, all monthly archives back for however long, etc.) for each build.

**Comment by gemfarmer** [comment]
Is this still being worked on?

**Comment by parkr** [comment]
@alfredxing At this point, I'd say try it. Worst case scenario, they run a full rebuild and the problem ceases. Time to rip off the bandaid :smiley:

**Comment by alfredxing** [comment]
Okie!

@mnot There are a couple of conflicts with my recent Page migration. I looked at them locally and they seemed easy to resolve. Can you rebase and take a look? 🙇

**Comment by mnot** [comment]
Sure. Might take a week or so, have a few things I need to do first.

**Comment by mnot** [comment]
Hmm, that problem with 1.9 seems to be an environment issue...

**Comment by parkr** [comment]
@mnot You're right! I'd say we can drop support for Jekyll 2.0 personally, but that's not really up to me here. @alfredxing can decide that. From the build error, it looks like we're trying to use Octokit 4.4.1, but Octokit 4.0 and above require Ruby 2.0 and above.

**Comment by paulrobertlloyd** [comment]
Reading through this conversation, seems like there’s little preventing this PR being accepted. Would be nice to get make this plugin compatible with incremental rebuilds. Any possibility of making the final push!?

**Comment by parkr** [comment]
Let's get this show on the road. @alfredxing, I'm going to merge this for now. Please file any issues/PR's if you'd like to see anything here change.

@jekyllbot: merge +minor

**Comment by paulrobertlloyd** [comment]
Yay! Thanks @parkr (and @mnot of course)!

**Pull request merged**
