### PR TITLE
Test against Jekyll 3

### PR DESCRIPTION
**Pull request by pathawks**
jekyll/jekyll#3945

One failing test with Jekyll 3:
```
  1) Failure:
TestJekyllArchives#test_: the jekyll-archives plugin with default config should not generate any archives.  [/home/travis/build/pathawks/jekyll-archives/test/test_jekyll_archives.rb:134]:
Expected: 0
  Actual: 12
```

### CODE REVIEW

**Comment by parkr** [comment]
LGTM. Not sure what's going on with that test. @alfredxing?

**Comment by alfredxing** [comment]
I'm guessing it has something to do with incremental regen, though I'll look into this more when I get home.

This plugin likely won't work with incremental regen, since the archive pages need the full content of posts/pages...

**Comment by pathawks** [comment]
If I set `full_rebuild: true`:
```
  1) Failure:
TestJekyllArchives#test_: the archives should populate the {{ site.archives }} tag in Liquid.  [jekyll-archives/test/test_jekyll_archives.rb:123]:
Expected: 12
  Actual: 3


  2) Failure:
TestJekyllArchives#test_: the jekyll-archives plugin with default config should not generate any archives.  [jekyll-archives/test/test_jekyll_archives.rb:134]:
Expected: 0
  Actual: 3

17 runs, 39 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by alfredxing** [comment]
@pathawks: Where are you setting `full_rebuild: true`? Setting it in the test file makes all of the tests pass for me locally (indicating that incremental regen is likely the culprit)

@parkr: Is there a way for a plugin to change the site's config to set `full_rebuild` (via a hook, or other means)?

**Comment by parkr** [comment]
> @parkr: Is there a way for a plugin to change the site's config to set full_rebuild (via a hook, or other means)?

@alfredxing You should be able to instantiate the Site with that in the config.

**Comment by alfredxing** [comment]
@parkr Ah, darn, the `full_rebuild` option is cached by `Regenerator` when it is initialized in `Site.config`, which means it can't really be changed. Would you prefer removing the caching, or adding a `pre_config` hook?

**Comment by parkr** [comment]
@alfredxing Does `Site#reset` help here?

**Comment by alfredxing** [comment]
I don't think so, since `reset` runs after `Regenerator` is instantiated.

**Comment by parkr** [comment]
@alfredxing [Doesn't it run `Regenerator#clear_cache`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/site.rb#L82)?

**Comment by alfredxing** [comment]
@parkr: Sorry for being confusing! What I mean is that the when `Regenerator` is instantiated, [its `@disabled` attribute is set](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/regenerator.rb#L146-L149). This attribute is used instead of re-reading the site config.

**Comment by parkr** [comment]
Ah! Interesting... In the meantime, you can hack around it with `site.instance_variable_set(:@disabled, false)` but maybe we clear that out at `#reset` in Jekyll core.

**Comment by pathawks** [comment]
Closing this in favor of #48 :+1:

**Pull request closed without merging**
